import type { User, WorkPost, Application, Message, Review, Notification } from "./types";

export const dummyUsers: User[] = [
  {
    id: "user-1",
    name: "Alex Rivera",
    email: "alex@example.com",
    password: "password123",
    username: "alexrivera",
    photo: "",
    bio: "Full-stack developer with 5+ years of experience in React, Node.js, and cloud architecture. Passionate about building scalable solutions.",
    skills: ["React", "Node.js", "TypeScript", "AWS", "PostgreSQL", "Docker"],
    location: "San Francisco, CA",
    portfolioLinks: ["https://alexrivera.dev", "https://github.com/alexrivera"],
    socialLinks: ["https://linkedin.com/in/alexrivera"],
    education: "BS Computer Science, Stanford University",
    experience: "Senior Developer at TechCorp (3 yrs), Frontend Lead at StartupX (2 yrs)",
    rating: 4.8,
    totalRatings: 24,
    completedWorks: 18,
    joinedDate: "2024-06-15",
  },
  {
    id: "user-2",
    name: "Priya Sharma",
    email: "priya@example.com",
    password: "password123",
    username: "priyasharma",
    photo: "",
    bio: "UI/UX designer specializing in mobile-first design systems. I help startups create beautiful, user-centric products.",
    skills: ["Figma", "UI Design", "UX Research", "Prototyping", "Design Systems", "Tailwind CSS"],
    location: "Mumbai, India",
    portfolioLinks: ["https://priya.design", "https://dribbble.com/priyasharma"],
    socialLinks: ["https://twitter.com/priyadesigns"],
    education: "MFA Interaction Design, NID Ahmedabad",
    experience: "Lead Designer at DesignLab (4 yrs), UX Consultant (Freelance, 2 yrs)",
    rating: 4.9,
    totalRatings: 31,
    completedWorks: 27,
    joinedDate: "2024-03-10",
  },
  {
    id: "user-3",
    name: "Marcus Chen",
    email: "marcus@example.com",
    password: "password123",
    username: "marcuschen",
    photo: "",
    bio: "Data scientist and ML engineer. Experienced in building recommendation systems and NLP pipelines.",
    skills: ["Python", "TensorFlow", "PyTorch", "SQL", "Data Analysis", "NLP"],
    location: "Toronto, Canada",
    portfolioLinks: ["https://marcuschen.io"],
    socialLinks: ["https://linkedin.com/in/marcuschen"],
    education: "MS Data Science, University of Toronto",
    experience: "ML Engineer at DataFlow (3 yrs), Data Analyst at FinTech Inc (2 yrs)",
    rating: 4.6,
    totalRatings: 15,
    completedWorks: 12,
    joinedDate: "2024-08-22",
  },
  {
    id: "user-4",
    name: "Sofia Martinez",
    email: "sofia@example.com",
    password: "password123",
    username: "sofiamartinez",
    photo: "",
    bio: "Content strategist and copywriter helping brands tell compelling stories through digital media.",
    skills: ["Copywriting", "SEO", "Content Strategy", "Social Media", "Brand Voice", "Analytics"],
    location: "Austin, TX",
    portfolioLinks: ["https://sofiacreates.com"],
    socialLinks: ["https://twitter.com/sofiacreates"],
    education: "BA Communications, UT Austin",
    experience: "Content Director at BrandHouse (3 yrs), Senior Copywriter at AdAgency (2 yrs)",
    rating: 4.7,
    totalRatings: 19,
    completedWorks: 15,
    joinedDate: "2024-05-01",
  },
  {
    id: "user-5",
    name: "James Okafor",
    email: "james@example.com",
    password: "password123",
    username: "jamesokafor",
    photo: "",
    bio: "DevOps and cloud infrastructure specialist. Automating everything from CI/CD to Kubernetes clusters.",
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Linux", "Monitoring"],
    location: "Lagos, Nigeria",
    portfolioLinks: ["https://jamesokafor.dev"],
    socialLinks: ["https://github.com/jamesokafor"],
    education: "BSc Computer Engineering, University of Lagos",
    experience: "DevOps Lead at CloudScale (4 yrs), SRE at InfraOps (2 yrs)",
    rating: 4.5,
    totalRatings: 11,
    completedWorks: 9,
    joinedDate: "2024-09-05",
  },
];

export const dummyWorkPosts: WorkPost[] = [
  {
    id: "work-1",
    title: "Build a React Dashboard for SaaS Analytics",
    category: "Web Development",
    shortDescription: "Need a modern analytics dashboard with charts, filters, and real-time data display.",
    detailedDescription: "Looking for an experienced React developer to build a comprehensive analytics dashboard for our SaaS platform. The dashboard should include interactive charts (line, bar, pie), date range filters, export functionality, and a responsive layout. Must integrate with our REST API for real-time data. We use Tailwind CSS for styling.",
    skills: ["React", "TypeScript", "Tailwind CSS", "Chart.js"],
    budgetMin: 2000,
    budgetMax: 4000,
    deadline: "2026-03-15",
    urgency: "medium",
    workType: "remote",
    location: "Remote",
    postedBy: "user-2",
    postedDate: "2026-02-10",
  },
  {
    id: "work-2",
    title: "Mobile App UI/UX Redesign",
    category: "Design",
    shortDescription: "Complete redesign of our fitness tracking mobile app for iOS and Android.",
    detailedDescription: "We need a talented UI/UX designer to completely overhaul our fitness tracking app. The current design is outdated and needs a modern, clean, intuitive interface. Deliverables include wireframes, high-fidelity mockups in Figma, a design system with reusable components, and handoff documentation for developers.",
    skills: ["Figma", "UI Design", "UX Research", "Mobile Design"],
    budgetMin: 3000,
    budgetMax: 6000,
    deadline: "2026-04-01",
    urgency: "high",
    workType: "remote",
    location: "Remote",
    postedBy: "user-1",
    postedDate: "2026-02-08",
  },
  {
    id: "work-3",
    title: "ML Model for Customer Churn Prediction",
    category: "Data Science",
    shortDescription: "Develop a machine learning model to predict customer churn for our subscription service.",
    detailedDescription: "We have 2 years of customer data and need a predictive model for churn analysis. The project includes data exploration, feature engineering, model training (Random Forest, XGBoost, or similar), evaluation, and deployment-ready code. Should include a Jupyter notebook with clear documentation.",
    skills: ["Python", "TensorFlow", "Data Analysis", "SQL"],
    budgetMin: 1500,
    budgetMax: 3500,
    deadline: "2026-03-20",
    urgency: "medium",
    workType: "remote",
    location: "Remote",
    postedBy: "user-4",
    postedDate: "2026-02-05",
  },
  {
    id: "work-4",
    title: "SEO Content Strategy for E-commerce Site",
    category: "Content & Marketing",
    shortDescription: "Create a comprehensive SEO content plan with 20 optimized blog posts.",
    detailedDescription: "Looking for an SEO expert to develop a content strategy for our e-commerce platform. Need keyword research, content calendar, 20 blog post outlines with target keywords, meta descriptions, and on-page optimization recommendations. Experience with e-commerce SEO is a must.",
    skills: ["SEO", "Content Strategy", "Copywriting", "Analytics"],
    budgetMin: 800,
    budgetMax: 1500,
    deadline: "2026-03-01",
    urgency: "low",
    workType: "remote",
    location: "Remote",
    postedBy: "user-3",
    postedDate: "2026-02-11",
  },
  {
    id: "work-5",
    title: "Set Up CI/CD Pipeline with Kubernetes",
    category: "DevOps",
    shortDescription: "Configure automated deployment pipeline with GitHub Actions and Kubernetes.",
    detailedDescription: "We need a DevOps engineer to set up a complete CI/CD pipeline using GitHub Actions for our microservices architecture. The pipeline should include automated testing, Docker image building, pushing to container registry, and deploying to our Kubernetes cluster. Also need monitoring setup with Prometheus and Grafana.",
    skills: ["Kubernetes", "CI/CD", "Docker", "Terraform"],
    budgetMin: 2500,
    budgetMax: 5000,
    deadline: "2026-03-10",
    urgency: "high",
    workType: "remote",
    location: "Remote",
    postedBy: "user-1",
    postedDate: "2026-02-09",
  },
  {
    id: "work-6",
    title: "WordPress E-commerce Store Setup",
    category: "Web Development",
    shortDescription: "Set up a WooCommerce store with custom theme and payment gateway integration.",
    detailedDescription: "Need a WordPress developer to build an e-commerce store using WooCommerce. Includes custom theme development, product catalog setup (50+ products), payment gateway integration (Stripe and PayPal), shipping calculator, and basic SEO setup. Mobile-responsive design is essential.",
    skills: ["WordPress", "WooCommerce", "PHP", "CSS"],
    budgetMin: 1200,
    budgetMax: 2500,
    deadline: "2026-03-25",
    urgency: "medium",
    workType: "remote",
    location: "Remote",
    postedBy: "user-5",
    postedDate: "2026-02-07",
  },
  {
    id: "work-7",
    title: "Brand Identity Design Package",
    category: "Design",
    shortDescription: "Complete brand identity including logo, color palette, typography, and guidelines.",
    detailedDescription: "We are launching a new tech startup and need a complete brand identity package. This includes logo design (3 concepts, 2 rounds of revisions), color palette, typography selection, brand guidelines document, social media templates, and business card design. Modern, minimal aesthetic preferred.",
    skills: ["Logo Design", "Brand Identity", "Figma", "Typography"],
    budgetMin: 1800,
    budgetMax: 3500,
    deadline: "2026-04-10",
    urgency: "low",
    workType: "remote",
    location: "Remote",
    postedBy: "user-3",
    postedDate: "2026-02-12",
  },
  {
    id: "work-8",
    title: "API Integration and Backend Development",
    category: "Backend Development",
    shortDescription: "Build REST API endpoints and integrate third-party services for our platform.",
    detailedDescription: "We need a Node.js backend developer to build REST API endpoints for user management, order processing, and notifications. Also need integration with Stripe for payments, SendGrid for emails, and Twilio for SMS. Must include proper error handling, validation, and API documentation.",
    skills: ["Node.js", "Express", "PostgreSQL", "REST API"],
    budgetMin: 3000,
    budgetMax: 5500,
    deadline: "2026-03-30",
    urgency: "high",
    workType: "hybrid",
    location: "New York, NY",
    postedBy: "user-2",
    postedDate: "2026-02-06",
  },
];

export const dummyApplications: Application[] = [
  {
    id: "app-1",
    workId: "work-1",
    applicantId: "user-1",
    proposalMessage: "I have extensive experience building React dashboards with real-time data. I previously built an analytics platform at TechCorp that handled 100K+ daily users. I can deliver this within 3 weeks.",
    referenceLink: "https://github.com/alexrivera/dashboard-demo",
    skillsUsed: ["React", "TypeScript", "Chart.js", "Tailwind CSS"],
    estimatedTime: "3 weeks",
    counterPrice: 3200,
    status: "accepted",
    appliedDate: "2026-02-11",
  },
  {
    id: "app-2",
    workId: "work-2",
    applicantId: "user-2",
    proposalMessage: "As a UI/UX designer specializing in mobile apps, I have redesigned 15+ apps in the fitness and health space. My design process includes user research, wireframing, prototyping, and usability testing.",
    referenceLink: "https://dribbble.com/priyasharma/fitness-app",
    skillsUsed: ["Figma", "UI Design", "UX Research", "Prototyping"],
    estimatedTime: "4 weeks",
    counterPrice: 4500,
    status: "pending",
    appliedDate: "2026-02-09",
  },
  {
    id: "app-3",
    workId: "work-3",
    applicantId: "user-3",
    proposalMessage: "I have built churn prediction models for 3 SaaS companies. My models typically achieve 85%+ accuracy. I will provide a complete Jupyter notebook with EDA, feature engineering, and model comparison.",
    referenceLink: "https://github.com/marcuschen/churn-model",
    skillsUsed: ["Python", "XGBoost", "Pandas", "scikit-learn"],
    estimatedTime: "2 weeks",
    counterPrice: 2800,
    status: "pending",
    appliedDate: "2026-02-06",
  },
  {
    id: "app-4",
    workId: "work-5",
    applicantId: "user-5",
    proposalMessage: "DevOps is my specialty. I have set up CI/CD pipelines for 10+ companies using GitHub Actions and Kubernetes. I will also include comprehensive monitoring with Prometheus and Grafana dashboards.",
    referenceLink: "https://github.com/jamesokafor/k8s-pipeline",
    skillsUsed: ["Kubernetes", "GitHub Actions", "Docker", "Prometheus"],
    estimatedTime: "2 weeks",
    counterPrice: 3800,
    status: "accepted",
    appliedDate: "2026-02-10",
  },
  {
    id: "app-5",
    workId: "work-4",
    applicantId: "user-4",
    proposalMessage: "Content strategy is what I do best. I have helped 20+ e-commerce brands increase organic traffic by 150%+ through targeted content strategies. I will deliver a data-driven plan with measurable KPIs.",
    referenceLink: "https://sofiacreates.com/case-studies/ecommerce-seo",
    skillsUsed: ["SEO", "Content Strategy", "Google Analytics", "Ahrefs"],
    estimatedTime: "10 days",
    counterPrice: 1200,
    status: "completed",
    appliedDate: "2026-02-06",
  },
];

export const dummyMessages: Message[] = [
  { id: "msg-1", senderId: "user-1", receiverId: "user-2", content: "Hi Priya! Thanks for accepting my application. I am excited to start working on the dashboard.", timestamp: "2026-02-11T10:30:00Z", read: true },
  { id: "msg-2", senderId: "user-2", receiverId: "user-1", content: "Hey Alex! Welcome aboard. Let me share the API documentation with you so you can get started.", timestamp: "2026-02-11T10:35:00Z", read: true },
  { id: "msg-3", senderId: "user-1", receiverId: "user-2", content: "That would be great. I have already set up the project structure. Should we schedule a call to discuss the requirements in detail?", timestamp: "2026-02-11T11:00:00Z", read: true },
  { id: "msg-4", senderId: "user-2", receiverId: "user-1", content: "Sure! How about tomorrow at 2pm EST? I will send you a calendar invite.", timestamp: "2026-02-11T11:15:00Z", read: false },
  { id: "msg-5", senderId: "user-5", receiverId: "user-1", content: "Hi Alex! I have started setting up the Kubernetes cluster. Quick question - are you using EKS or self-managed?", timestamp: "2026-02-11T09:00:00Z", read: true },
  { id: "msg-6", senderId: "user-1", receiverId: "user-5", content: "We are using EKS. I will share the AWS credentials securely. Let me set up an IAM role for you.", timestamp: "2026-02-11T09:30:00Z", read: true },
  { id: "msg-7", senderId: "user-5", receiverId: "user-1", content: "Perfect, EKS makes things much smoother. I will prepare the Terraform configurations for the cluster setup.", timestamp: "2026-02-11T10:00:00Z", read: false },
];

export const dummyReviews: Review[] = [
  { id: "rev-1", fromUserId: "user-3", toUserId: "user-4", workId: "work-4", rating: 5, comment: "Sofia delivered an exceptional content strategy. Organic traffic increased by 180% within 2 months. Highly recommended!", date: "2026-02-12" },
  { id: "rev-2", fromUserId: "user-4", toUserId: "user-3", workId: "work-4", rating: 4, comment: "Marcus was a great client to work with. Clear requirements and timely feedback. Would work with again.", date: "2026-02-12" },
  { id: "rev-3", fromUserId: "user-2", toUserId: "user-1", workId: "work-1", rating: 5, comment: "Alex is an outstanding developer. The dashboard exceeded our expectations with beautiful visualizations and smooth performance.", date: "2026-01-20" },
  { id: "rev-4", fromUserId: "user-1", toUserId: "user-5", workId: "work-5", rating: 5, comment: "James set up an incredible CI/CD pipeline. Deployments went from 2 hours to 5 minutes. Absolute professional.", date: "2026-01-25" },
];

export const dummyNotifications: Notification[] = [
  { id: "notif-1", userId: "user-1", type: "accepted", message: "Your application for 'Build a React Dashboard' was accepted!", read: false, date: "2026-02-11" },
  { id: "notif-2", userId: "user-1", type: "message", message: "New message from Priya Sharma", read: false, date: "2026-02-11" },
  { id: "notif-3", userId: "user-1", type: "application", message: "New application received for 'Mobile App UI/UX Redesign'", read: true, date: "2026-02-09" },
  { id: "notif-4", userId: "user-1", type: "completed", message: "Work 'SEO Content Strategy' has been marked as completed", read: true, date: "2026-02-12" },
];

export const categories = [
  "Web Development",
  "Design",
  "Data Science",
  "Content & Marketing",
  "DevOps",
  "Backend Development",
  "Mobile Development",
  "Blockchain",
  "AI & Machine Learning",
  "Video & Animation",
];
