spring.application.name=backend
server.port=8080

spring.mongodb.uri=mongodb+srv://rohit:rohit0811@proconnect.rtkgvra.mongodb.net/proconnect?retryWrites=true&w=majority&appName=proconnect

cloudinary.cloud-name=dd4s9ife4
cloudinary.api-key=541583497765428
cloudinary.api-secret=zbpuzF6gwkJ7ZJrCr0_pAINQQ5k

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

server.tomcat.max-swallow-size=-1
server.tomcat.max-part-count=50
server.tomcat.max-parameter-count=1000